

pool:
  name: news
  vmImage: ubuntu-latest

steps:
 - script: sudo  apt-get update  -y
 - script: sudo  apt-get install maven -y
 - task: CopyFiles@2
   inputs:
     SourceFolder: '$(System.DefaultWorkingDirectory)'
     Contents: |
      **/*.xml
     TargetFolder: '$(Build.ArtifactStagingDirectory)'
 - task: PublishBuildArtifacts@1
   inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'